### PR TITLE
use sodium-native

### PR DESCRIPTION
**Pull request by akostylev0**

### CODE REVIEW

**Comment by TT10234** [comment]
> 

작업시작합시당

**Comment by TT10234** [comment]
Gogo

**Review by rahat007420 — APPROVED** [review]

**Comment by Emmydon049** [comment]
Ton coin

**Comment by Emmydon049** [comment]
Ton coin

**Comment by Emmydon049** [comment]
> Ton coin

Yes

**Review by Emmydon049 — COMMENTED** [review]
- -[ ]

**Review by Emmydon049 — COMMENTED** [review]
Ton cion

**Pull request merged**
